### ISSUE TITLE
Chapter 4 - Sidecar exercise

### ISSUE THREAD

**Issue by septst** [bmuschko/ckad-prep#9]
Hello,

I am on the chapter 4 - questions 7 to 10. I have the below manifest.

```
apiVersion: v1
kind: Pod
metadata:
  name: data-exchange
spec:
  containers:
  - image: busybox
    name: main-app
    command: ['sh', '-c', 'counter=1; while true; do touch \
              "/var/app/data/$counter-data.txt"; counter=$((counter+1)); \
              sleep 30; done']
    volumeMounts:
    - name: data-dir
      mountPath: /var/app/data
    resources: {}
  - image: busybox
    name: sidecar
    command: ['sh', '-c', 'while true; do ls -d /var/app/data/*-data.txt \
              | wc -l; sleep 30; done']
    volumeMounts:
    - name: data-dir
      mountPath: /var/app/data
  volumes:
  - name: data-dir
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
```

But, I am seeing errors in logs of both the `main-app` and `sidecar` containers.

In `sidecar` logs,

```
ls: /var/app/data/*-data.txt: No such file or directory
ls:  : No such file or directory
0
ls: /var/app/data/*-data.txt: No such file or directory
ls:  : No such file or directory
0
```

In  `main-app` logs,

```
touch:  /var/app/data/463608-data.txt: No such file or directory
sh:  sleep: not found
touch:  /var/app/data/463609-data.txt: No such file or directory
sh:  sleep: not found
touch:  /var/app/data/463610-data.txt: No such file or directory
sh:  sleep: not found
```

Can you please advise on what I am doing wrong? I tried updating the manifest `mountPath` with and without double quotes. Thank you.
